#
#  Copyright 2012 NVIDIA Corporation
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

CC       = pgcc
CCFLAGS  = -I$(CUDA_HOME)/include
ACCFLAGS = -acc -ta=tesla -Minfo=accel

BIN =  laplace2d_acc

all: $(BIN)

laplace2d_acc: laplace2d.c
	$(CC) $(CCFLAGS) $(ACCFLAGS) -o $@ $< -L$(CUDA_HOME)/lib64 -lnvToolsExt

clean:
	$(RM) $(BIN)
